config/routes.rb
Rails.application.routes.draw do
  root "pseudos#index"
  resources :pseudos do
    post 'upvote'
  end
end

app/models/pseudo.rb
class Pseudo < ActiveRecord::Base
  validates :fake_name, presence: true
  validates :fake_name, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pseudos_controller.rb
class PseudosController < ApplicationController
  before_action :set_pseudo, only: [:show, :edit, :update, :destroy]

  def index
    @q = Pseudo.search(params[:q])
    @pseudos = @q.result.sort_by { |pseudo| pseudo.votes }.reverse
    @last_pseudos = Pseudo.last(3).reverse
  end

  def show
  end

  def new
    @pseudo = Pseudo.new
  end

  def upvote
    @pseudo = Pseudo.find(params[:pseudo_id])
    @pseudo.votes += 1
    @pseudo.save
    redirect_to root_path
  end

  def edit
  end

  def create
    @pseudo = Pseudo.new(pseudo_params)
    if @pseudo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @pseudo.update(pseudo_params)
        format.html { redirect_to @pseudo, notice: 'Pseudo was successfully updated.' }
        format.json { render :show, status: :ok, location: @pseudo }
      else
        format.html { render :edit }
        format.json { render json: @pseudo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pseudo.destroy
    respond_to do |format|
      format.html { redirect_to pseudos_url, notice: 'Pseudo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pseudo
      @pseudo = Pseudo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pseudo_params
      params.require(:pseudo).permit(:fake_name, :real_name, :votes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pseudos_helper.rb
module PseudosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pseudo4fun</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/pseudos/_form.html.erb
<div class="form-group">

  <%= form_for(@pseudo) do |f| %>
    <% if @pseudo.errors.any? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4>Fish!</h4>
        <ul>
        <% @pseudo.errors.full_messages.each do |message| %>
          <li>Le champ <%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <div class="form-group">
        <%= f.label :fake_name, "pseudo" %>
        <%= f.text_field :fake_name, placeholder: "make me laugh", class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :real_name, "who's that?" %>
        <%= f.text_field :real_name, placeholder: "tell me the real name", class:'form-control' %>
      </div>
      <%= f.submit class:'btn btn-treehouse' %>
  <% end %>
</div>

app/views/pseudos/edit.html.erb
<h1>Editing Pseudo</h1>

<%= render 'form' %>

<%= link_to 'Show', @pseudo %> |
<%= link_to 'Back', pseudos_path %>

app/views/pseudos/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to root_path, class:'logo' do %>
  pseudo<span>4</span>fun.
<% end %>


<div class="container">

  <div class="row">
    <div class="col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-3">
      <div class="search-form">
        <%= search_form_for @q, id:"search-form" do |f| %>
          <i class="glyphicon glyphicon-search"></i>
          <%= f.search_field :fake_name_cont, placeholder: 'rechercher parmi les pseudos...' %>
          <%= f.submit "hit enter!", class:'btn' %>
        <% end %>
      </div>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h5><strong>last entries</strong></h5>
          <%= link_to new_pseudo_path do %>
            new pseudo
          <% end %>
        </div>
        <div class="panel-body">
          <ul>
            <% @last_pseudos.each do |pseudo| %>
              <li>
                <strong><%="#{pseudo.fake_name}"%></strong> <span><%="(#{time_ago_in_words(pseudo.created_at)} ago)" %></span>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h5><strong>pseudos</strong></h5>
          <span class="badge">total : <%= @pseudos.count %></span>
        </div>
        <% @pseudos.each do |pseudo| %>
          <div class="item">
            <%= link_to pseudo_upvote_path(pseudo), class:'item-upvote', method: 'post' do %>
              <div class="item-arrow"></div>
              <div class='item-count'><%= pseudo.votes %></div>
            <% end %>
            <div class='item-body'>
              <h3><%= pseudo.fake_name %></h3>
              <p><%= pseudo.real_name %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pseudos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= render 'form' %>
      <%= link_to 'Back', pseudos_path %>
    </div>
  </div>
</div>

app/views/pseudos/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <h1>
            <%= @pseudo.fake_name %>
          </h1>
          <h4 class="realname">
            <%= @pseudo.real_name %>
          </h4>
          <p class="label label-warning">
            <%= pluralize(@pseudo.votes, 'vote') %>
          </p>
        </div>
      </div>
      <%= link_to 'Back', pseudos_path %>
    </div>
  </div>
</div>